export const runtime = "nodejs";

import { pool } from "../../../../lib/db";
import { NextResponse } from "next/server";
import { verifyAdminAccess } from "../../../../lib/adminAuth";

export async function GET(req: Request) {
  try {
    const admin = await verifyAdminAccess(req);
    if (!admin) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const userId = searchParams.get("userId");

    if (!userId) {
      return NextResponse.json(
        { error: "userId is required" },
        { status: 400 },
      );
    }

    // Get user details
    const userRes = await pool.query(
      `
      SELECT 
        id,
        email,
        name,
        mobile,
        address,
        default_cow_price,
        default_buffalo_price,
        brand_milk_name,
        default_brand_price,
        created_at,
        is_active
      FROM users
      WHERE id = $1 AND is_admin = FALSE
      `,
      [userId],
    );

    if (userRes.rows.length === 0) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const user = userRes.rows[0];

    // Get user's milk entries count and total
    const entriesRes = await pool.query(
      `
      SELECT 
        COUNT(*) as total_entries,
        SUM(liters) as total_liters,
        SUM(total_amount) as total_revenue
      FROM milk_entries
      WHERE user_id = $1
      `,
      [userId],
    );

    const entries = entriesRes.rows[0];

    // Get milk type breakdown
    const breakdownRes = await pool.query(
      `
      SELECT 
        milk_type,
        SUM(liters) as total_liters,
        SUM(total_amount) as total_amount,
        COUNT(*) as entry_count,
        AVG(price_per_liter) as avg_price
      FROM milk_entries
      WHERE user_id = $1
      GROUP BY milk_type
      `,
      [userId],
    );

    // Get last entry date
    const lastEntryRes = await pool.query(
      `
      SELECT date 
      FROM milk_entries
      WHERE user_id = $1
      ORDER BY date DESC
      LIMIT 1
      `,
      [userId],
    );

    const lastEntry = lastEntryRes.rows[0];

    // Get recent entries (last 5)
    const recententriesRes = await pool.query(
      `
      SELECT 
        id,
        date,
        milk_type,
        liters,
        price_per_liter,
        total_amount
      FROM milk_entries
      WHERE user_id = $1
      ORDER BY date DESC
      LIMIT 5
      `,
      [userId],
    );

    // Get monthly trends
    const monthlyTrendsRes = await pool.query(
      `
      SELECT 
        DATE_TRUNC('month', date) as month,
        COUNT(*) as entry_count,
        SUM(liters) as total_liters,
        SUM(total_amount) as total_amount
      FROM milk_entries
      WHERE user_id = $1
      GROUP BY DATE_TRUNC('month', date)
      ORDER BY month DESC
      LIMIT 6
      `,
      [userId],
    );

    // Get performance metrics
    const metricsRes = await pool.query(
      `
      SELECT 
        AVG(liters) as avg_liters_per_entry,
        (SELECT COUNT(DISTINCT date) FROM milk_entries WHERE user_id = $1) as unique_entry_days,
        (SELECT EXTRACT(DAY FROM NOW() - created_at) FROM users WHERE id = $1) as days_since_signup
      FROM milk_entries
      WHERE user_id = $1
      `,
      [userId],
    );

    const metrics = metricsRes.rows[0];
    const daysSinceSignup = metrics?.days_since_signup || 0;
    const uniqueEntryDays = metrics?.unique_entry_days || 0;

    // Get bills generated by user
    const billsRes = await pool.query(
      `
      SELECT 
        id,
        bill_type,
        year,
        month,
        from_date,
        to_date,
        total_amount,
        created_at
      FROM bills
      WHERE user_id = $1
      ORDER BY created_at DESC
      LIMIT 10
      `,
      [userId],
    );

    return NextResponse.json({
      user: {
        ...user,
        created_at: user.created_at,
      },
      stats: {
        total_entries: Number(entries.total_entries) || 0,
        total_liters: parseFloat(entries.total_liters) || 0,
        total_revenue: parseFloat(entries.total_revenue) || 0,
        last_entry_date: lastEntry?.date || null,
        account_age_days: Math.floor(daysSinceSignup) || 0,
        avg_liters_per_entry: parseFloat(metrics?.avg_liters_per_entry) || 0,
        unique_entry_days: Number(uniqueEntryDays) || 0,
      },
      breakdown: breakdownRes.rows.map((row) => ({
        milk_type: row.milk_type,
        total_liters: parseFloat(row.total_liters) || 0,
        total_amount: parseFloat(row.total_amount) || 0,
        entry_count: Number(row.entry_count),
        avg_price: parseFloat(row.avg_price) || 0,
      })),
      recentEntries: recententriesRes.rows.map((row) => ({
        id: row.id,
        date: row.date,
        milk_type: row.milk_type,
        liters: parseFloat(row.liters) || 0,
        price_per_liter: parseFloat(row.price_per_liter) || 0,
        total_amount: parseFloat(row.total_amount) || 0,
      })),
      monthlyTrends: monthlyTrendsRes.rows.map((row) => ({
        month: row.month,
        entry_count: Number(row.entry_count),
        total_liters: parseFloat(row.total_liters) || 0,
        total_amount: parseFloat(row.total_amount) || 0,
      })),
      bills: billsRes.rows.map((row) => ({
        id: row.id,
        bill_type: row.bill_type,
        year: Number(row.year),
        month: Number(row.month),
        from_date: row.from_date,
        to_date: row.to_date,
        total_amount: parseFloat(row.total_amount) || 0,
        created_at: row.created_at,
      })),
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
